# Generated by Django 6.0.1 on 2026-01-16 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='guide_license_document',
            field=models.FileField(blank=True, help_text='Carnet/acreditación oficial de guía (PDF/JPG/PNG).', null=True, upload_to='verification/guide_license/'),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='insurance_or_registration_document',
            field=models.FileField(blank=True, help_text='Seguro RC o alta de autónomo/empresa (PDF/JPG/PNG).', null=True, upload_to='verification/insurance_or_registration/'),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notas internas (motivo de rechazo, observaciones, etc.).'),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Staff que verificó el perfil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_guides', to=settings.AUTH_USER_MODEL),
        ),
    ]
