# Generated by Django 6.0.1 on 2026-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_guideprofile_guide_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil (JPG/PNG).', null=True, upload_to='guides/avatars/'),
        ),
    ]
