# Generated by Django 6.0.1 on 2026-01-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_guideprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
