# Generated by Django 6.0.1 on 2026-01-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('traveler', 'Traveler'), ('guide', 'Guide')], default='traveler', max_length=20),
        ),
    ]
