# Generated by Django 6.0.1 on 2026-01-16 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('daily_capacity_people', models.PositiveIntegerField(blank=True, help_text='Capacidad total de personas por día (vacío = sin límite).', null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='experiences.experience')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='availability.experienceavailability')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('availability', 'date')},
            },
        ),
    ]
