# Generated by Django 6.0.1 on 2026-01-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceavailability',
            name='daily_capacity_bookings',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo de excursiones (reservas aceptadas) por día. Vacío = sin límite.', null=True),
        ),
    ]
