# Generated by Django 6.0.1 on 2026-01-16 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='experiences.category'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['is_active'], name='experiences_is_acti_0da7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['price'], name='experiences_price_2dd01a_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['duration_minutes'], name='experiences_duratio_364be9_idx'),
        ),
    ]
