# Generated by Django 6.0.1 on 2026-01-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_category_experience_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='tags',
            field=models.CharField(blank=True, help_text='Palabras clave separadas por comas. Ej: timanfaya, volcanes, lava', max_length=255),
        ),
    ]
