# Generated by Django 6.0.1 on 2026-01-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helparticle',
            options={'ordering': ['-is_featured', 'title'], 'verbose_name': 'Help article', 'verbose_name_plural': 'Help articles'},
        ),
    ]
