# Generated by Django 6.0.1 on 2026-01-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_helparticle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Help category', 'verbose_name_plural': 'Help categories'},
        ),
    ]
