# Generated by Django 6.0.1 on 2026-01-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_guide_response_booking_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seen_by_guide',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seen_by_traveler',
            field=models.BooleanField(default=True),
        ),
    ]
