# Generated by Django 6.0.1 on 2026-01-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_seen_by_guide_booking_seen_by_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(default=0, help_text='Niños 2-11 (50%)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='infants',
            field=models.PositiveIntegerField(default=0, help_text='Bebés 0-1 (gratis)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport_mode',
            field=models.CharField(choices=[('own_vehicle', 'Vehículo propio'), ('minibus', 'Minibus (recogida)'), ('other', 'Otro / por definir')], default='own_vehicle', max_length=20),
        ),
    ]
