# Generated by Django 6.0.1 on 2026-01-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_adults_booking_children_booking_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
