# Generated by Django 6.0.1 on 2026-01-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_meeting_point_booking_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
