# Generated by Django 6.0.1 on 2026-01-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_responded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
