# Generated by Django 6.0.1 on 2026-01-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='transport_mode',
            field=models.CharField(choices=[('own_vehicle', 'Vehículo propio'), ('minibus', 'Minibus (recogida)'), ('bicycle', 'Bicicleta'), ('by foot', 'A pie')], default='own_vehicle', max_length=20),
        ),
    ]
