# Generated by Django 6.0.1 on 2026-01-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='preferred_language',
            field=models.CharField(choices=[('', 'Selecciona un idioma'), ('es', 'Español'), ('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('pt', 'Português')], max_length=5),
        ),
    ]
