# Generated by Django 6.0.1 on 2026-01-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('change_requested', 'Change requested'), ('cancel_requested', 'Cancel requested')], default='pending', max_length=20),
        ),
    ]
